name: Release
on:
  release:
    types:
      - published

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Latest
        if: github.event.release.prerelease == false
        id: docker_build_latest
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          tags: |
            ghcr.io/devfolioco/siwe-oidc:${{ github.event.release.tag_name }}
            ghcr.io/devfolioco/siwe-oidc:latest
          build-args: |
            INFURA_ID=${{ secrets.INFURA_ID }}
            WALLET_CONNECT_ID=${{ secrets.WALLET_CONNECT_ID }}
      - name: Build and push Pre-Release
        if: github.event.release.prerelease == true
        id: docker_build_prerelease
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # @todo Add arm builds once they are faster
          platforms: linux/amd64
          tags: |
            ghcr.io/devfolioco/siwe-oidc:${{ github.event.release.tag_name }}
          build-args: |
            INFURA_ID=${{ secrets.INFURA_ID }}
